import { EngineConfigurationOption, Text } from '@sonolus/core'

export const optionsDefinition = {
    speed: {
        name: Text.Speed,
        standard: true,
        advanced: true,
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    hidden: {
        name: Text.Hidden,
        standard: true,
        advanced: true,
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    noteSpeed: {
        name: Text.NoteSpeed,
        scope: 'LLSIF',
        type: 'slider',
        def: 9,
        min: 1,
        max: 11,
        step: 0.1,
    },
    attribute: {
        name: 'Attribute',
        scope: 'LLSIF',
        type: 'select',
        def: 0,
        values: ['Original', 'Smile', 'Pure', 'Cool'] as string[],
    },
    mirror: {
        name: Text.Mirror,
        type: 'toggle',
        def: 0,
    },
    sfxEnabled: {
        name: Text.Effect,
        scope: 'LLSIF',
        type: 'toggle',
        def: 1,
    },
    autoSFX: {
        name: Text.EffectAuto,
        scope: 'LLSIF',
        type: 'toggle',
        def: 0,
    },
    noteSize: {
        name: Text.NoteSize,
        scope: 'LLSIF',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    noteEffectEnabled: {
        name: Text.NoteEffect,
        scope: 'LLSIF',
        type: 'toggle',
        def: 1,
    },
    noteEffectSize: {
        name: Text.NoteEffectSize,
        scope: 'LLSIF',
        type: 'slider',
        def: 1,
        min: 0.1,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    connectorAlpha: {
        name: Text.ConnectorAlpha,
        scope: 'LLSIF',
        type: 'slider',
        def: 0.5,
        min: 0.1,
        max: 1,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    previewVerticalScale: {
        name: Text.PreviewScaleVertical,
        scope: 'LLSIF',
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: Text.PercentageUnit,
    },
    previewMeasure: {
        name: Text.PreviewMeasure,
        scope: 'LLSIF',
        type: 'toggle',
        def: 1,
    },
    previewBeat: {
        name: Text.PreviewBeat,
        scope: 'LLSIF',
        type: 'toggle',
        def: 1,
    },
    previewTime: {
        name: Text.PreviewTime,
        scope: 'LLSIF',
        type: 'toggle',
        def: 1,
    },
    previewBpm: {
        name: Text.PreviewBpm,
        scope: 'LLSIF',
        type: 'toggle',
        def: 1,
    },
} satisfies Record<string, EngineConfigurationOption>
